default: &default
  twitter_consumer_key: "xxxxxxxxxxxxxxxxxxxxxxx"
  twitter_consumer_secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

  development:
    <<: *default

    test:
      <<: *default

      production:
        twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"]%>
        twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"]%>
